### ISSUE TITLE
Support for requiring multiple API Key security requirements

### ISSUE THREAD

**Issue by Sn0wCrack** [vyuldashev/laravel-openapi#58]
It appears there's no way currently (or at least documented way I can find) to require more than one API Key header for the Security Requirements.

It looks like the OpenAPI documentation specify this is possible: https://swagger.io/docs/specification/authentication/api-keys/

```
  components:
    securitySchemes:
      apiKey:
        type: apiKey
        in: header
        name: X-API-KEY
      appId:
        type: apiKey
        in: header
        name: X-APP-ID
  security:
    - apiKey: []
      appId:  []   # <-- no leading dash (-)
```

It would be good if this was supported to allow for requiring more than one security header.
